version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  publish_nuget: true
  verbosity: minimal
  
build_script:
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet pack -o ../nugetpack -c release

artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: NuGet
  server: https://www.myget.org/F/aelf/api/v2/package
  api_key:
    secure: Lta8u6yYcPzwEzPPHOWWOr+ZYOpa2jde4gVKkTA3qT6C/xgqwG8wDvkoaegBblmW
  on:
    branch: master
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  auth_token:
    secure: GXp2XRUEjXquQFkS7fKuVupitolb3d+P2Mge4yKBjoGgwpw9W7m6Yv45AA0B6mcX
  artifact: /.*\.nupkg/
  on:
    branch: master